import { combineReducers } from 'redux';
import BooksReducer from './reducer_books';

const rootReducer = combineReducers({
  // this is global application state
  books: BooksReducer
  // key is name of piece of state. value is reducer itself
});

// when we pass it to combineReducers, we're telling Redux how to define our application state

export default rootReducer;


// Application state is generated by reducer functions
